tonistiigi/fsutil

diskwriter.go, diskwriter_linux.go, diskwriter_windows.go, receive.go, send.go, tarsum.go, walker.go
This add supports for Windows for diskwriter and send/receive components.
This is key to enable context streaming / tardiffs on Windows.
2 scenarios remain to test: windows client -> linux daemon and linux
client -> windows daemon.
=> Windows support for send/receive tardiffs.

send.go
When rewriting rights for Windows, I introduced a bug removing the directory flag.
This fix that with a simple ored value.
=> Fix introduced bug on rights re-writing for folders on Windows

walker.go, walker_test.go
Allows overriding and filtering walked files, for example for resetting uid/gid.
cc @shouze
=> Add filter support for walker

send.go
Before these would be cleaned up by the `gc` and could cause `too many open files` errors.
@fcrisciani
=> fix fd leak on send

receive.go
fixes 2 possible cases for not handling sender error properly:
- When context gets canceled, it could cause the id from `r.pipes` to get deleted. Now, if sender goroutine sends more data the pipe would not be found.
- When `fill()` gets canceled, `update()` could get blocked if it manages to fill channel buffer before it itself gets canceled.
@AkihiroSuda 
=> avoid possible receiver panic/deadlock on sender error

walker.go
This can cause a race on copy when a big destination directory that is still being walked is deleted. 
=> avoid not-exist error on walker

receive.go, receive_test.go
Make sure the grpc stream is fully read. Otherwise, stream completes with an error for the monitoring tools when the context is canceled.
=> receive: read stream to EOF on close

receive.go, receive_test.go, send.go
=> Fixes an error propagation bug that resulted in a hang

copy/copy.go, copy/copy_test.go
=> copy: Fixes bug when relative destination does not have a directory component

diskwriter.go, diskwriter_test.go, receive_test.go
Also removes some redundant import-aliases
Noticed this while looking at https://github.com/tonistiigi/fsutil/issues/26#issuecomment-393506311 earlier today
ping @tonistiigi @AkihiroSuda
=> Fix "expected" and "actual" being swapped in test

diskwriter.go, receive.go
This matches the same transformation as is done in `DiskWriter.Handle`, which
eventually gets passed to the `AsyncDataCb` AKA `receiver.asyncDataFunc` which
performs the lookup.
This matters on Windows where `filepath.FromSlash` will convert `/` into `\`.
I've tested this (in the context of buildkit) with a Linux `sender` and Windows
`receiver`, I've no capability to test the opposite direction.
Signed-off-by: Ian Campbell <ijc@docker.com>
=> receive: convert file path to local form when registering.

bench/util.go, cmd/walk/walk.go, copy/copy_test.go, diskwriter_test.go
- Marked `RequiresRoot` as helper, so that line-numbers match in output, and unexported it
- Removed the `fileInfo` type, as it was no longer used since https://github.com/tonistiigi/fsutil/commit/195d62bee906e45aa700b8ebeb3417f7b126bb23 (https://github.com/tonistiigi/fsutil/pull/7)
=> Minor cleanups in tests and imports

chtimes_nolinux.go, diskwriter.go, receive_test.go, walker.go
fixes #26 
@thaJeztah Thanks for bringing my attention to this.
There are some fixes in here that are mostly just for making the test compatible with non-linux and non-root user, but two cases also need to be checked when vendoring this to buildkit. These are:
- handling the size on directory records (now resets to 0)
- handling mode of symlinks. This is tricky because it is only supported on linux (and even then with some crazy hacks). I think we need to detect it in buildkit hash function as well and force set.
This also fixes the chtimes issue that showed up on darwin. I'm not sure why this one was not failing for anyone else.
=> Fixes for non-root/symlink copy tests

followlinks.go, followlinks_test.go, walker.go, walker_test.go
This allows setting paths on a walker that are evaluated as symlinks and the target paths on these paths are added to the includepatterns.
This enables fixing the cases where a Dockerfile context detection can make sure that if the source path that user requested is a symlink, the target path is included in the context as well.
=> Allow followed symlinks on walker

bench/diffcopy.go, cmd/send/send.go, fs.go, receive_test.go, send.go
This changes the input of send from strict walker options for a more generic `FS` interface.
The second commit uses the `FS` interface to allow wrapping the sent files to a dynamic subdirectory.
@tiborvass
=> Allow dynamic subdir wrapper for send

copy/copy_linux.go
In `s390x` if run in limited caps `copy_file_range` returns `EPERM` instead of `ENOSYS` causing the copy to fail. Add a workaround to ignore `EPERM` as well that should be safe as no other case should return it. Have reported this to continuity where this code originated.
=> fix copy_file_range on s390x

.travis.yml, go.sum
It seems that there was a bugfix between `go1.11` and `go1.11.5` that causes `go.sum` checksums to differ and `go mod tidy` to fail on `go1.11.5` with: 
```
verifying gotest.tools@v2.2.0+incompatible: checksum mismatch
downloaded: h1:VsBPFP1AI068pPrMxtb/S8Zkgf9xEmTLJjfM+P5UIEo=
go.sum:     h1:y0IMTfclpMdsdIbr6uwmJn5/WZ7vFuObxDMdrylFM3A=
```
New go.sum generated with go1.11.5
=> update go.sum with go1.11.5

receive.go
Context canceling was not properly handled in the case the fill already passed first select and could cause a deadlock if the channel buffer was full. Analysis based on https://gist.github.com/cpuguy83/da1d7af5b6a21a3cc10adaf8d7e66d73 trace.
=> receive: fix possible deadlock on error

copy/copy.go, copy/copy_linux.go, copy/copy_test.go, copy/copy_unix.go, copy/copy_windows.go, copy/mkdir.go, copy/mkdir_unix.go, copy/mkdir_windows.go
updates for the copy package required for https://github.com/moby/buildkit/pull/809
Contains fs root protection as the code doesn't need to run in a container anymore, and support for non-followlinks mode. Some of the previous functionality is refactored to exposed more public functions for controlling wildcards and mkdirp.
@AkihiroSuda @tiborvass
=> copy: updates for buildkit fileop

copy/copy.go
This allows the caller of this function to get the original basename of the path. The caller itself should protect the return value with `RootPath` if needed. 
=> copy: remove rootpath from resolvewildcards

stat_unix.go
fix for https://github.com/moby/buildkit/issues/877
The issue appeared if there were more than two hardlinks pointing to the same source causing the validation to fail. The change is to always point them on the same file.
=> fix sending more than two hardlinks

diskwriter.go, receive_test.go, walker.go, walker_test.go
Extends the current filter callback so that filters can also access the file path, not only the fileinfo structure. Enables adding filters for things similar to https://github.com/moby/buildkit/issues/874
=> allow checking file path on filters

copy/copy.go, copy/copy_darwin.go, copy/copy_linux.go, copy/copy_test.go, copy/copy_unix.go, copy/copy_windows.go
=> copy: add fast copy path for darwin

diff.go, diff_containerd.go, diskwriter.go, receive.go, receive_test.go, types/stat.go
Make sure filter is taken into an account when comparing existing files in the receiver. This issue prevents incremental transfers with userns because the metadata on disk is always different than the one being transferred.
=> receive: use filter on receive diff

copy/copy_linux.go, copy/copy_unix.go, copy/stat_bsd.go, copy/stat_sysv.go, go.mod, go.sum
These wrappers replace the use of the utility functions in `github.com/containerd/containerd/sys`, and work around https://github.com/golang/go/issues/32887.
The implementations were derived from https://golang.org/search?q=Stat_t#Global_pkg/syscall
Hence, `containerd/containerd` is no longer used and can be removed as a dependency, which also removes `Microsoft/hcsshim`.
=> Create local atime/mtime wrappers for syscall.Stat_t

tarwriter.go
The tarwriter treats symlink as hardlinks. This leads to the tar exporter issue [here](https://github.com/moby/buildkit/issues/1411).
=> Fix symlink in tarwriter

receive_test.go, stat_test.go
=> - [*] skip tests that would fail in Debian-build, closes #76

.travis.yml, stat_unix.go, walker.go
follow-up to https://github.com/tonistiigi/fsutil/pull/81
=> Drop support for go1.12, and use errors.Is() for error-detection

walker.go
spotted on buildkit ci https://travis-ci.org/github/moby/buildkit/jobs/709029993#L3587
This was actually attempted to be fixed before but the previous fix https://github.com/tonistiigi/fsutil/pull/54/files did not take into account that stdlib could already be returning this error, therefore only narrowing the race.
=> walker: fix notadir error

chtimes_nolinux.go, diff.go, diskwriter.go, diskwriter_unix.go, followlinks.go, fs.go, hardlinks.go, send.go, stat.go, tarwriter.go, validator.go, walker.go
Improving error returns:
- more typed errors
- remove extra verbosity (eg. PathError already contains action and path)
- ensure stack traces are added to errors
=> improving error returns

.github/workflows/ci.yml, .travis.yml, docker-bake.hcl
Add CI based on github actions through bake targets. Travis can remain enabled for now as well.
=> Add github action CI

copy/copy_darwin.go, go.mod, go.sum
Use the `Clonefileat` wrapper from `golang.org/x/sys/unix` instead of
manually implementing it using `unix.Syscall6(SYS_CLONEFILEAT, ...)`
direct syscall which are no longer supported on macOS.
=> copy: use Clonefileat from golang.org/x/sys/unix on macOS

copy/copy_linux.go
=> copy: add more copy_file_range exceptions

copy/copy.go, copy/copy_test.go, prefix/match.go, prefix/match_test.go, walker.go, walker_test.go
Allow include patterns and exclude patterns to be specified, similarly
to `Walker`.
There is a bit of extra complexity to handle the case of a pattern like
`a/*/c`. In this case, creating the directories `a` and `a/b` may need
to be delayed until we encounter `a/b/c`.
cc @hinshun
=> Add IncludePatterns and ExcludePatterns options for Copy

copy/copy.go, copy/copy_test.go
This changes the logic for copy's "include patterns" to use
`PatternMatcher`, so it behaves the same as "exclude patterns". This is a
net simplification and provides more consistency between the two
parameters (for example, include patterns can now specify negative
matches), but is a bit worse performance-wise (we can't skip a directory
which fails to partially match a pattern, because files inside it may
match the pattern).
cc @hinshun
=> Use PatternMatcher for copy include patterns as well as exclude patterns

bench/go.sum, copy/copy.go, copy/copy_test.go, go.mod, go.sum, walker.go
This updates fsutil to use the new methods introduced in
https://github.com/moby/moby/pull/42676. This fixes the issue with
patterns like `**/foo` which was the motivation for that fix.
cc @coryb
=> Use updated PatternMatcher Matches methods for pattern matching

.github/workflows/ci.yml, copy/copy_freebsd.go, copy/copy_unix.go, diskwriter_freebsd.go, diskwriter_unix.go, diskwriter_unixnobsd.go, docker-bake.hcl, hack/Vagrantfile.freebsd13, receive_test.go
Currently `copy` and `diskwriter` packages can't be built on FreeBSD:
- copy package lacks implementation of `copyFile` & `copyFileContent`
functions.
- diskwriter package assumes 32-bit device nodes, and FreeBSD uses 64
ones.
This change
* Fixes FreeBSD build issues
* Fixes tests
* Introduces a GH Actions job to run tests on FreeBSD.
Signed-off-by: Artem Khramov <akhramov@pm.me>
=> FreeBSD port

copy/copy_linux.go
This ports an err handling fix from
https://github.com/containerd/continuity/commit/23a11df3824c0e2868cff8775369f3cbd3430226
Signed-off-by: Alex Couture-Beil <alex@earthly.dev>
=> ports err handling from containerd/continuity

bench/go.sum, copy/copy.go, copy/copy_test.go, go.mod, go.sum, walker.go
Adjust for changes in https://github.com/moby/moby/pull/43037
=> Adjust fileutils to use corrected MatchesUsingParentResults function

copy/copy_linux.go
This is a follow up to abe942fbd8b232a2a4ffac5226264af1dc08a0e5
where I missed the final `return nil` from https://github.com/containerd/continuity/commit/23a11df3824c0e2868cff8775369f3cbd3430226
for the cases where no error occurs and the fallback userspace copy succeeded
Signed-off-by: Alex Couture-Beil <alex@earthly.dev>
=> return when io.CopyBuffer finishes

.github/workflows/ci.yml
fixes #118 
Looks like PR to add vagrant/virtualbox on MacOS 11 runners has been closed https://github.com/actions/virtual-environments/pull/4010 so in the meantime use `macos-10.15` [as suggested](https://github.com/actions/virtual-environments/issues/4060#issuecomment-950757410).
Signed-off-by: CrazyMax <crazy-max@users.noreply.github.com>
=> fix(ci): vagrant not available on macos 11 runners

walker.go
If a dir doesn't match the include patterns, and no include patterns can
possibly match any children, don't bother traversing it.
If a dir matches the exclude patterns, and no exceptions to the exclude
patterns can possibly match any children, don't bother traversing it.
=> Avoid traversal of directories whose children are impossible to match

walker.go
`filepath.Walk` may pass a nil value of `fi` when `walkErr` is non-nil. The
usual case is that `fi` is also non-nil, so this wasn't found by tests.
=> Fix panic when fi is nil in walk callback

hack/dockerfiles/lint.Dockerfile
Something bizarre going on here that I don't really understand.
Without `gcc` being present linter will show following warnings:
```
#27 5.475 copy/copy.go:399:19: invalid operation: cannot compare c.changefn != nil (operator != not defined on untyped nil) (typecheck)
#27 5.475 	if c.changefn != nil {
#27 5.476 	                 ^
#27 5.477 copy/copy.go:7:2: "path" imported but not used (typecheck)
#27 5.477 	"path"
#27 5.477 	^
#27 5.478 ../../../../../usr/local/go/src/runtime/cgo/cgo.go:34:8: could not import C (cgo preprocessing failed) (typecheck)
#27 5.478 import "C"
#27 5.479        ^
```
These don't make sense to me. First could be lack of understanding of types by the linter, second one is just wrong because `path` is used. This will only happen when there is not previous …
=> hack: add gcc back to lint

copy/copy.go, copy/copy_test.go
Before this, if a directory was excluded, copy would still end up
getting called with overwriteTargetMetadata=true in the code path where
subdirs of the root of the src are iterated over. This meant that even
though the target directory was never created and never existed, the
copyFileInfo bool would stay its default value of true and the code
would try to copy file info to a directory that doesn't exist.
This update just adds a check to see if the target dir actually exists
and sets copyFileInfo to false if not.
Signed-off-by: Erik Sipsma <erik@sipsma.dev>
=> copy: don't copy file info of non-existent dir.

diskwriter.go, receive_test.go
:hammer_and_wrench: Fixes the bug reported in https://github.com/moby/buildkit/issues/2884#issuecomment-1301028540.
This is needed as creating files in directories modifies their timestamp, so we need to set the timestamp again after creating all the directory contents.
This logic is similar to the logic in [diffapply_unix.go in moby/buildkit](https://github.com/moby/buildkit/blob/master/snapshot/diffapply_unix.go#L142).
=> receiver: re-apply directory timestamps after copying

copy/copy.go, copy/copy_linux.go, copy/copy_test.go, copy/copy_unix.go, copy/copy_windows.go
:hammer_and_wrench: Fixes https://github.com/moby/buildkit/issues/2884
We need to restore the previous directory `FileInfo` if it existed prior to attempting to copy content into it.
=> copy: restore parent directory timestamp after copying contents

copy/copy.go, copy/copy_linux.go, copy/copy_unix.go, copy/copy_windows.go, copy/mkdir.go, copy/mkdir_unix.go, copy/mkdir_windows.go, go.mod
This change adds the ability to copy Windows file ownership and security information, as well as implement proper Chown() for Windows.
Signed-off-by: Gabriel Adrian Samfira <gsamfira@cloudbasesolutions.com>
=> Add Windows file ownership code

send.go
CopyBuffer may not always use the provided buffer, in the case that the src implements WriterTo. So, in the case that the io.ReadCloser returned by fs.Open implements this method, the packet size limit will not be enforced, creating an oversized packet that results in an error on the receiver.
To avoid this, we can create an anonymous structure to wrap the src, which prevents the shortcut taken by the standard library.
I'm not 100% sure of the approach for this, maybe we should write our own `Copy` method to circumvent this issue instead?
cc @crazy-max
=> Always use buf in CopyBuffer

bench/go.mod, bench/go.sum, copy/copy_test.go, copy/copy_unix_test.go, copy/copy_windows.go, copy/mkdir_windows.go, go.mod, go.sum
The c.chowner function was being ignored. This change makes use of the supplied chowner and calls Chown() on the file. If no chowner is specified, we copy over the DACL and owner information from the source.
This change also adds tests and copies timestamps on Windows.
This splits up #143 a bit.
=> Fix copy on windows plus tests

followlinks.go, followlinks_test.go, followlinks_unix.go, followlinks_windows.go
This change handles Windows absolute paths and properly handles IsNotFound errors.
This change also fixes tests on Windows.
Signed-off-by: Gabriel Adrian Samfira <gsamfira@cloudbasesolutions.com>
=> Fix follow symlinkResolver on Windows

diskwriter.go, diskwriter_unix.go, diskwriter_windows.go
Symlinks on Windows are implemented using NTFS reparse points. Reparse points are also used when creating volume mounts on Windows. As far as golang is concerned, mountpoints and symlinks look the same. This change makes the distinction between the two and allows safely renaming symlinks, while erring out for anything else that looks like a symlink.
Signed-off-by: Gabriel Adrian Samfira <gsamfira@cloudbasesolutions.com>
=> Implement proper renameFile on Windows

copy/mkdir_windows.go
We need to check that the user is not nil before de-referencing it.
=> Fix potential nil pointer dereference

copy/mkdir_windows.go
The ```EnableProcessPrivileges()``` function will enable a certain set of privileges for the entire process. I am unsure if enabling/disabling privileges is tracked with some sort of reference counting, but if it's not, when we release those privileges, we disable them for the entire process. This means that if some other go routine requires them, we may end up with undesirable results.
The ```RunWithPrivileges()``` function locks the thread in which the function runs, and enables those privileges only in that thread.
=> Use RunWithPrivileges

diskwriter.go
Remove the break statement that prevented the file from being closed.
=> Fix leaking file handle

diskwriter.go
If using the diskwriter hanlders in parallel we might see a common directory being created in parallel, only one will win.  This allows us to gracefully retry/re-evaluate when we get a syscall.EEXIST error on the mkdir instead of returning an error.
=> handle mkdir race for diskwriter

cmd/send/send.go, cmd/walk/walk.go, filter.go, filter_test.go, followlinks.go, followlinks_test.go, fs.go, fs_test.go, receive_test.go, send.go, tarwriter.go
This patch creates a new FilterFS to pair with a new FilterOpt, which contains the old WalkOpt parameters.
Essentially, this splits the functionality of the old FS into a new FS and the FilterFS. The new FS implemenation simply performs operations over a specified local filesystem, while the FilterFS wraps an existing FS implementation to apply filtering patterns.
This allows the same logic for filtering to apply to *any* underlying filesystem, for example, the StaticFS and MergeFS implementations in BuildKit (see https://github.com/moby/buildkit/pull/4094).
To do this, we also make some reasonably substantial changes to the developer-facing API. We need to use fs.WalkDirFunc instead of the old filepath.WalkFunc, which is required to preserve the lazy stat() semantics from …
=> fs: split out include/exclude into new FilterFS

.github/workflows/ci.yml
We got a bunch of warnings in CI:
This PR updates actions to latest stable to fix this issue and also split jobs to reduce build time a bit more.
=> ci: update actions to fix warnings and split jobs

copy/copy.go, copy/copy_test.go
Before this, copy would always refuse to replace an existing path in the dest with something from the source of a different type. E.g. if there was a symlink at the dest, you'd get an error if copying src meant replacing the symlink w/ a directory.
This is the right default behavior but there are situations in which callers may want to opt in to instead always replacing what's in dest with what's in source.
This adds an option to enable that behavior.
---
cc @tonistiigi @jedevc PTAL, if we're good with adding this option I'll follow up with adding this option to LLB's `CopyInfo` too.
=> Add support for always overwriting existing paths

filter.go
=> chore: fix typos in NewFilterFS docstring

copy/copy_linux.go, copy/copy_unix.go, copy/copy_unix_test.go
This PR fixes `(*copier).copyFileInfo()` to respect special bits specified in the copier struct. It causes [the BuildKit issue](https://github.com/moby/buildkit/issues/3920) where `COPY --chmod` doesn't respect the most significant octet of the Unix Permission.
This behavior might be intended because setting setuid/setgid to an executable file was known as an anti-pattern in terms of security. However, this command should not ignore them implicitly if the user understands its drawbacks and desires to set them.
It seems Go's `os.FileMode` has its internal representation of special bits. We need to convert special bits to internal representation to set them properly. 
> Additionally, when os.Chmod() runs, it [actively discards](https://cs.opensource.google/go/go/+/refs/tags/go1.17.6:src/os/f …
=> copy: fix to respect most significant octet of given permission in copyFileInfo

.github/workflows/ci.yml, hack/Vagrantfile.freebsd13
related to: https://github.com/tonistiigi/fsutil/actions/runs/7375943482/job/20068119491#step:4:30
This is similar to what has been done on buildkit repo:
* https://github.com/moby/buildkit/pull/4486
* https://github.com/moby/buildkit/pull/4363
* https://github.com/moby/buildkit/pull/4147
* https://github.com/moby/buildkit/pull/4378
=> ci: freebsd job enhancements

filter.go, filter_test.go
Original issue found by @vito in https://github.com/dagger/dagger/issues/6687.
Split into two commits, both with slightly different issues:
- `filter: allow SkipDir return with lazy parents`. Ensures that walker functions that return `filepath.SkipDir` are always respected, even when evaluated as a lazy parent function (see commit for more details).
- `filter: ensure MapResult is followed for parent directories`. Ensures that the `FilterFS` Map option for `MapResultSkipDir` is always respected, even when evaluated as a lazy parent function (see commit for more details).
These issues seem to have been present for a while (including prior to #167, which introduced `FilterFS`, where the issue was still present in `fsutil.Walk`).
- The first issue seems to have appeared in …
=> Fix `FilterFS` when skipping lazy parent directories

send.go
fixes https://github.com/docker/buildx/issues/2207
closes #186
related to https://github.com/docker/buildx/issues/2207#issuecomment-1957316154
alternative to #186 to make sure unix-style path is sent through the wire so we don't need extra conversion on the receiver side.
cc @jedevc @gabriel-samfira
=> send: ensure file path to unix form when sending files

receive_test.go, send.go
Fixes a silly data race where progressCurrent is incremented (and later accessed) by 1 of 4 threads.
=> fix data race in progressCb

diskwriter.go
Previously, it was possible for errors returned by an asyncronous callback function to not be propagated, and to instead return "context canceled" from `Receive`.
This could happen based on this specific sequence of events:
- An asyncronous callback is called from `HandleChange`, and returns an error, completing the async errorgroup context with an error state.
- Another call to `HandleChange` completes, and uses the context syncronously, returning `context.Canceled`.
- This in turn propagates to `doubleWalkDiff`, which returns the canceled error, instead of calling `Wait` which would contain the actual error group error.
This behavior is racy, based on exactly how and when the asyncronous callback is called.
The fix to this is relatively straightforward: we just need to make sure that …
=> receive: ensure callback errors are propagated

diff_containerd.go, diskwriter.go, receive.go
This PR should fix file transfers from Windows to Linux (as is the case with docker-on-windows), and fixes https://github.com/moby/buildkit/pull/4806 https://github.com/moby/buildkit/issues/4741 (cc @profnandaa)
Also fixes https://github.com/dagger/dagger/issues/6923.
There are two parts, split into separate commits. This also could probably do with some tests :smile: 
Essentially, this change is wrong (cc @crazy-max): https://github.com/tonistiigi/fsutil/pull/173/files#diff-7dd945edf522324729284de47c3bdb062155cc945eaec235fc564631ae4e91b5
The validator consumes data *directly* off of the wire, which is guaranteed to be in unix-path form (see https://github.com/moby/buildkit/pull/4806#pullrequestreview-1965145911). Therefore, we should avoid using the platform-specific `filepath` package, …
=> Fix file transfers from windows to linux

receive.go, send.go
Follow-up from https://github.com/tonistiigi/fsutil/pull/196#pullrequestreview-2007019635.
I *think* this is the right approach?
I'm kinda of struggling to understand what the desired interface is here - the sender is fairly straightforward, since we just host an `FS` object (which is platform-specific). The receiver is a bit harder, since it can take a filter function, and various `include`/`exclude` parameters - should those functions refer to platform-specific paths? Or should they refer to unix-style wire paths?
This feels like it would fix the issue where the linknames are wrong (I think this was introduced in https://github.com/tonistiigi/fsutil/pull/173, when we started explicitly converting to unix paths on the wire). Something doesn't feel right here though.
=> recv: translate linkname to wire format

hardlinks.go, receive_test.go, send.go
fix https://github.com/moby/buildkit/issues/4831
With the refactor to FilterFS the hardlink handling was changed so that the hardlink detection is in a separate FS instance and then FilterFS is layered on top of it. This means that the file that was the source for the hardlink could be filtered out, but the Stat pointing to that link is still sent as is.
New function validates if source files are not present in FS anymore and correct the linking. It could be better if all the FS implementation did this automatically, but there is quite a lot of layering going on atm. with multiple layers of FilterFS that would all need to keep own hardlink memory, so atm. the new function is only called before send.
=> fix hardlink filter regression

bench/diffcopy.go
Fix for this:
```
src/github.com/tonistiigi/fsutil/bench/diffcopy.go:24:31: multiple-value fsutil.NewFS(src, nil) (value of type (fsutil.FS, error)) in sin
gle-value context
src/github.com/tonistiigi/fsutil/bench/diffcopy.go:24:49: too many arguments in call to fsutil.NewFS
have (string, nil)
want (string)
```
=> Fixup fallout with new FS changed API

types/stat.go
The stat clone returned by protobuf returns a version of `types.Stat` that isn't compatible with some tests in buildkit. This changes clone to create a new type without cloning the hidden protobuf types.
=> types: stat clone drops hidden proto fields

bench/go.mod, bench/go.sum, copy/copy.go, copy/copy_linux.go, copy/copy_unix.go, copy/copy_unix_test.go, copy/copy_windows.go, go.mod, go.sum
prerequisite for https://github.com/moby/buildkit/issues/1951
=> copy: add support for non-octal mode setting

copy/copy.go, copy/copy_test.go, copy/mkdir.go
=> fix correcting timestamps for created destination dir after copy

copy/copy_openbsd.go, copy/copy_unix.go, copy/stat_openbsd.go
This fixes https://github.com/docker/buildx/issues/2772
=> Fixed build on OpenBSD

.github/workflows/ci.yml, docker-bake.hcl, hack/Vagrantfile.openbsd
follow-up https://github.com/tonistiigi/fsutil/pull/215#pullrequestreview-2410707460
cc @catap
=> build and test openbsd

Dockerfile, hack/dockerfiles/lint.Dockerfile
This fixes compatibility with alpine 3.21 and file 5.46+
- Fix additional possible `xx-cc`/`xx-cargo` compatibility issue with Alpine 3.21
- Support for Alpine 3.21
- Fix `xx-verify` with `file` 5.46+
- Fix possible error taking lock in `xx-apk` in latest Alpine without `coreutils`
full diff: https://github.com/tonistiigi/xx/compare/v1.5.0...v1.6.1
=> update xx to v1.6.1 for compatibility with alpine 3.21 and file 5.46+

filter.go
fix https://github.com/moby/buildkit/issues/5625
The patterns returned in the error message were missing the ones added via opts.FollowLinks
=> fix error message for invalid includepatterns

.github/workflows/ci.yml, hack/Vagrantfile.freebsd, hack/Vagrantfile.netbsd, hack/Vagrantfile.openbsd
relates to: https://github.com/tonistiigi/fsutil/actions/runs/14326752686/job/40153584558#step:6:68
```
==> default: Machine booted and ready!
==> default: Installing rsync to the VM...
==> default: Rsyncing folder: /home/runner/work/fsutil/fsutil/ => /vagrant
==> default: Running provisioner: init (shell)...
default: Running: inline script
default: pkg already bootstrapped at /usr/local/sbin/pkg
default: Updating FreeBSD repository catalogue...
default: FreeBSD repository is up to date.
default: All repositories are up to date.
default: pkg: No packages available to install matching 'go123' have been found in the repositories
```
This is similar to https://github.com/moby/buildkit/pull/5893 but instead we can install Go from official binary release like we have done on Buildx repo: …
=> ci: fix freebsd package repository

buffer.go, buffer_test.go, receive.go, receive_test.go
This optional mode allows skipping transferring the file data if remote side just hopes to analyze how the local files look like.
=> Allow metadata-only receivers

stat_test.go, stat_unix.go
Extended attributes from `com.apple` will bust remote layer caches
and shouldn't be transferred to a Linux environment. Skip loading these
extended attributes as part of loading xattrs.
Fixes docker/for-mac#7636.
Replaces moby/buildkit#5899.
Original credit to @tylermichael for creating an initial solution.
=> stat: ignore apple extended attributes
