tonistiigi/fsutil

cmd/receive/receive.go
cmd/send/send.go
util/protostream.go

fix compilation error in cmd/{send, receive}

---

receive.go
receive_test.go

Add progress support to receiver side

---

.travis.yml
bench/diffcopy.go
cmd/receive/receive.go

add travis

---

validator.go

fix windows path validation

---

bench/bench_test.go
diff_containerd_linux.go
diskwriter_unix.go
walker_unix.go

The repository moved to the containerd org
ping @stevvooe @tonistiigi

Update github.com/stevvooe/continuity import path

---

walker.go
walker_test.go

walker: handle parents and subdirs in includepatterns

---

diskwriter_test.go

diskwriter: fix concurrent map access in tests

---

.travis.yml

update go version in travis

---

diskwriter.go

When syncing files that are readonly (0111), the sync fails (and sometimes even panic, due to a synchronization problem).
The problem is that the file is created on the receiver with the same rights as the sender, thus making it unopenable in Write mode on the receiver.
This commit checks permission errors on opening files, record current file mode (for reapplying it on closing) and chmod to make it writeable.
Not sure how to test that properly though

Fix an issue where syncing read only files

---

copy/copy.go

copy: don't copy over the metadata of existing destination directory

---

bench/diffcopy.go
cmd/receive/receive.go
cmd/send/send.go
cmd/walk/walk.go
diff.go
diff_containerd.go
diskwriter.go
diskwriter_test.go
receive.go
receive_test.go
send.go
util/protostream.go
walker.go
walker_test.go

ping @tonistiigi @tiborvass PTAL

Switch from x/net/context to context

---

walker.go
walker_test.go

walker: fix bug in prefix match

---

diff_containerd.go
diskwriter.go
diskwriter_test.go
receive_test.go

fix issues tracking file mode changes

---

copy/copy.go

Docker creates dest dirs as 0755 https://github.com/moby/moby/blob/master/pkg/archive/archive.go#L1108
@tiborvass @AkihiroSuda 

copy: change perms of dest directory

---

walker_unix.go

walker: handle unsupported xattrs

---

copy/copy.go

Related https://github.com/moby/buildkit/issues/640

copy: chown the destination directories

---

.travis.yml
diskwriter_test.go
receive.go

update travis to go1.11

---

walker.go

When a directory is deleted a files parent dir may be deleted as well causing the stat functions to return `ENOTDIR` instead of `ENOENT`. Noticed this in buildkit CI.

walker: allow enotdir as enoent

---

copy/copy.go
copy/copy_linux.go
copy/copy_nowindows.go
copy/copy_unix.go

copy: add XAttrErrorHandler

---

go.mod
go.sum

go.mod cleanup

---

fs.go
receive_test.go
tarwriter.go

Add tarwriter and refactor `FS` so that memory-only subdirs can be exported with the tarball.
@AkihiroSuda

add tarwriter

---

stat.go
stat_test.go
validator_test.go
walker_test.go

Treat Unix sockets as regular files

---

go.mod
go.sum

fix gocrypto commit

---

copy/copy.go
copy/copy_linux.go
copy/mkdir.go

Refactor chown support to check old value to support https://github.com/moby/moby/issues/40335

copy: refactor chowner to check old value

---

.travis.yml
copy/copy_unix.go

copy: fix chowner on darwin

---

receive_test.go

fix test flakiness

---

receive_test.go

conflicting changes in #85 & #86 

fix test error from merge conflict

---

.travis.yml

Travis enables tty but can't actually handle the dynamic progress.

travis: force plain progress

---

go.mod
go.sum

full diff: https://github.com/opencontainers/go-digest/compare/v1.0.0-rc1...v1.0.0

go.mod: update opencontainers/go-digest v1.0.0

---

.github/workflows/ci.yml

github: test go1.15

---

docker-bake.hcl

Add linux/386

---

Dockerfile

update Dockerfile to v1.2

---

.github/workflows/ci.yml

github: add testing go 1.16

---

diff_containerd.go
receive.go

receive: add differ selection

---

walker.go
walker_test.go

A recent change to `Walk` causes it to walk dirs that matched an exclude
pattern, in cases where there are exceptions to the exclude pattern (do
we have better terminology for this?). This was done in order to support
exclusions like:
foo
!**/bar
In that example, we want to walk `foo` even though it's excluded,
because there might be a file or directory `bar` somewhere underneath
it.
However, this change in behavior surfaced "permission denied" errors
that didn't show up before. In the case that there is no permission to
list contents of "foo", that now results in an error.
To handle this properly, we need to ignore EPERM errors on dirs that we
are only accessing to search for these hypothetical nested files/dirs
which might end up included.
A followup change will optimize this behavior …

Handle EPERM errors when walking excluded dirs

---

.github/workflows/ci.yml

github: fix freebsd CI

---

.github/workflows/ci.yml
Dockerfile
chtimes_linux.go
copy/copy_nowindows.go
copy/hardlink_unix.go
copy/mkdir_unix.go
copy/stat_sysv.go
diskwriter_unix.go
diskwriter_unixnobsd.go
hack/dockerfiles/gomod.Dockerfile
hack/dockerfiles/lint.Dockerfile
hack/dockerfiles/shfmt.Dockerfile
hack/lint
receive_test.go
stat_unix.go

Dockerfile: add cache mounts for gomod

---

Dockerfile

Dockerfile: update xx to 1.1.0

---

walker_test.go

fixes https://github.com/tonistiigi/fsutil/issues/129

test: fix tests on systems with different umask defaults

---

.github/workflows/ci.yml
hack/dockerfiles/lint.Dockerfile

relates to https://github.com/tonistiigi/fsutil/pull/136

gha: update go versions to 1.18, 1.19

---

copy/copy_darwin.go

Downstream issue: https://github.com/macOScontainers/buildkit/issues/1

Fix cross-device copy failing on macOS

---

.github/workflows/ci.yml
diff_containerd.go
diskwriter_test.go
diskwriter_unix_test.go
filter.go
filter_test.go
followlinks.go
fs_test.go
receive_test.go
stat.go
validator.go
validator_test.go

ci: add windows to test matrix

---

.github/workflows/ci.yml

related to https://github.com/tonistiigi/fsutil/actions/runs/7833378605/job/21376479021#step:4:8

ci: fix test step for windows

---

.github/dependabot.yml
.github/workflows/ci.yml

related to https://github.com/tonistiigi/fsutil/actions/runs/7869231701

ci: bump actions to latest stable

---

.github/workflows/ci.yml

this is for manual testing from fork.

ci: set workflow_dispatch event

---

.github/workflows/ci.yml
hack/Vagrantfile.freebsd

similar to https://github.com/moby/buildkit/pull/5353

ci: switch to ubuntu runner for freebsd job

---

.github/workflows/ci.yml
copy/copy_otherbsd.go
copy/copy_unix.go
docker-bake.hcl
hack/Vagrantfile.netbsd

similar to https://github.com/tonistiigi/fsutil/pull/216
cc @akhramov @catap

netbsd: fixes, build and test

---

copy/copy.go
copy/copy_test.go
copy/copy_unix_test.go
copy/copy_windows_test.go

fix for https://github.com/moby/buildkit/issues/4945

copy: fix custom chmod for parent directories
